//
//  XMLParserKeys.h
//  AVPlayerSample
//
//  Created by Arun Dhwaj on 03/12/14.
//  Copyright (c) 2014 Tapasya Tandon. All rights reserved.
//

#ifndef AVPlayerSample_XMLParserKeys_h
#define AVPlayerSample_XMLParserKeys_h

//common
#define VAST                    @"VAST"
#define AD                      @"Ad"
#define INLINE                  @"InLine"
#define ADSYSTEM                @"AdSystem"
#define ADTITLE                 @"AdTitle"
#define DESCRIPTION             @"Description"
#define ADVERTISER              @"Advertiser"
#define VAST_ERROR              @"Error"
#define VAST_IMPRESSION         @"Impression"
#define CREATIVES               @"Creatives"
#define CREATIVE                @"Creative"
#define LINEAR                  @"Linear"
#define ICONS                   @"Icons"
#define ICON                    @"Icon"
#define ICONCLICKS              @"IconClicks"
#define DURATION                @"Duration"
#define TRACKINGEVENTS          @"TrackingEvents"
#define ADPARAMETERS            @"AdParameters"
#define VIDEOCLICKS             @"VideoClicks"
#define MEDIAFILES              @"MediaFiles"
#define MEDIAFILE               @"MediaFile"
#define ID                      @"id"
#define DELIVERY                @"delivery"
#define TYPE                    @"type"
#define BITRATE                 @"bitrate"
#define SKIPOFFSET              @"skipoffset"
#define COMPANIONADS            @"CompanionAds"
#define COMPANION               @"Companion"
#define ADID                    @"AdID"
#define SEQUENCE                @"sequence"
#define TRACKING                @"Tracking"
#define EVENT                   @"event"
#define CREATIVEVIEW            @"creativeView"
#define START                   @"start"
#define FIRSTQUARTILE           @"firstQuartile"
#define MIDPOINT                @"midpoint"
#define THIRDQUARTILE           @"thirdQuartile"
#define COMPLETE                @"complete"
#define MUTE                    @"mute"
#define UNMUTE                  @"unmute"
#define RESUME                  @"resume"
#define CLOSE                   @"close"
#define SKIP                    @"skip"
#define PAUSE                   @"pause"
#define OFFSET                  @"offset"
#define CLICKTHROUGH            @"ClickThrough"
#define CLICKTRACKING           @"ClickTracking"
#define CUSTOMCLICK             @"CustomClick"
#define STATICRESOURCE          @"StaticResource"
#define HTMLRESOURCE            @"HTMLResource"
#define CREATIVETYPE            @"creativeType"
#define IFRAMERESOURCE          @"IFrameResource"
#define COMPANION_CLICK_THROUGH @"CompanionClickThrough"
#define COMPANION_CLICK_TRACKING @"CompanionClickTracking"
#define ICONCLICKTRACKING       @"IconClickTracking"
#define ICONCLICKTHROUGH        @"IconClickThrough"
#define ICONVIEWTRACKING        @"IconViewTracking"
#define PROGRAM                 @"program"
#define XPOSITION               @"xPosition"
#define YPOSITION               @"yPosition"
#define HEIGHT                  @"height"
#define WIDTH                   @"width"

#define SEQUENCE                @"sequence"
#define APIFRAMEWORK            @"apiFramework"
#define CODEC                   @"codec"
#define ALTTEXT                 @"AltText"
#define ASSETWIDTH              @"assetWidth"
#define ASSETHEIGHT             @"assetHeight"
#define EXPANDEDWIDTH           @"expandedWidth"
#define EXPANDEDHEIGHT          @"expandedHeight"
#define ADSLOTID                @"adSlotId"
#define SCALABLE                @"scalable"
#define MINBITRATE              @"minbitrate"
#define MAXBITRATE              @"maxbitrate"
#define MAINTAINASPECTRATIO     @"maintainAspectRatio"
#define REQUIRED                @"required"
#define VERSION                 @"version"

#define MODEL                   @"&model=%@"
#define CURRENCY                @"currency"
#define SURVEY                  @"Survey"

#define VIDEOHUB                @"VideoHub"
#define FIRST                   @"first"
#define SEC                     @"sec"
#define THI                     @"thi"
#define DURATION_L              @"duration"
#define POSITION_OFFSET         @"positionOffset"

//                              @"video"

#define VAST_WIDTH              @"width"
#define VAST_HEIGHT             @"height"
#define VAST_REFRESH_TIME       @"refreshtime"
#define VAST_PLAYER_HEIGHT      @"playerHeight"
#define VAST_CONTENT_BAR_HEIGHT @"contentBarHeight"
#define VAST_GUID               @"guid"
#define VAST_CAMPAIGN_ID        @"campaignid"
#define VAST_CREATIVE_ID        @"creativeid"
#define VAST_TRACKING_URL       @"tracking_url"
#define VAST_ERROR_URL          @"error_url"
#define VAST_TEXT_COLOR         @"text_color"
#define VAST_BANNER_BG          @"banner_bg"
#define VAST_CLICK_URL          @"click_url"
#define VAST_USE_CLICK_URL      @"use_click_url"
#define VAST_CREATIVE_URL       @"creative_url"
#define VAST_IS_TAG             @"istag"
#define VAST_CICON              @"cicon"
#define VAST_OPEN_IN_BROWSER    @"click_open_in_browser"
#define VAST_RFLAG              @"rflag"
#define VAST_CLICK_DELAY        @"click_delay"
#define VAST_CLICK_CONFIRM      @"click_confirm"
#define VAST_ADD_CLOSE          @"add_close"
#define VAST_AD_PARAMS          @"adparams"
#define VAST_VIDEOBG            @"videoBg"
#define VAST_ISTAGENDCARD       @"istagEndcard"
#define VAST_CONTENTBAR         @"contentBar"
#define VAST_ADTYPE             @"adtype"
#define VAST_ISTAGCONTENTBAR    @"istagContentbar"
#define VAST_CLOSE_REFRESH_TIME @"close_refreshtime"
#define VAST_CLICK_REFRESH_TIME @"click_refreshtime"
#define VAST_CDD                @"cdd"
#define VAST_STATUS             @"status"
#define VAST_MESSAGE            @"message"
#define VAST_AD_ERROR           @"error"
#define VAST_AD_TYPE            @"ad_type"
#define VAST_AD_SUB_TYPE        @"ad_sub_type"
#define VAST_ENABLE_IFRAME      @"enableIframe"

#define VIDEO_TYPE              @"video/mp4"

#endif
